title: Project

files:
  sortable: true

pages: false

fields:

  title:
    label: Title
    type:  text
    width: 3/4
    
  client:
    label: Client
    type: text
    width: 1/3

  type:
    label: Project Type
    type: text
    width: 1/3

  year:
    label: Year
    type:  text
    width: 1/3

  text:
    label: Text
    type:  textarea

  pictures:
    label: Gallery
    type: gallery
    aspectRatio: 1:0.6
    displayFilename: false